
  addons:
    postgresql: "9.4"
    services:
      - postgresql
before_script:
  - psql -c 'create database myapp;' -U postgres
  - psql -c "CREATE USER myapp WITH PASSWORD 'dbpass';" -U postgres
language: java
